<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ingredients = [
            [
                'id' => 1,
                'name' => 'Bumbu Rendang Instan',
                'unit' => 'pcs',
                'price_per_unit' => 15000.00,
                'description' => 'Bumbu praktis untuk membuat rendang otentik',
                'stock_quantity' => 100,
                'minimum_stock_level' => 10,
                'image_url' => 'bumbu_rendang.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 2,
                'name' => 'Tepung Bumbu Krispi',
                'unit' => 'pcs',
                'price_per_unit' => 8000.00,
                'description' => 'Tepung bumbu serbaguna super renyah',
                'stock_quantity' => 150,
                'minimum_stock_level' => 20,
                'image_url' => 'tepung_krispi.jpg',
                'ingredient_category_id' => 3,
            ],
            [
                'id' => 3,
                'name' => 'Saus Sambal Bawang',
                'unit' => 'botol',
                'price_per_unit' => 20000.00,
                'description' => 'Sambal bawang pedas gurih',
                'stock_quantity' => 80,
                'minimum_stock_level' => 5,
                'image_url' => 'sambal_bawang.jpg',
                'ingredient_category_id' => 4,
            ],
            [
                'id' => 4,
                'name' => 'Kaldu Jamur Alami',
                'unit' => 'pcs',
                'price_per_unit' => 12000.00,
                'description' => 'Penyedap rasa non-MSG',
                'stock_quantity' => 200,
                'minimum_stock_level' => 20,
                'image_url' => 'kaldu_jamur.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 5,
                'name' => 'Daging Sapi Segar',
                'unit' => 'gram',
                'price_per_unit' => 140.00,
                'description' => 'Daging sapi bagian paha',
                'stock_quantity' => 5000,
                'minimum_stock_level' => 500,
                'image_url' => 'daging_sapi.jpg',
                'ingredient_category_id' => 2,
            ],
            [
                'id' => 6,
                'name' => 'Daging Ayam',
                'unit' => 'gram',
                'price_per_unit' => 50.00,
                'description' => 'Daging ayam potong segar',
                'stock_quantity' => 10000,
                'minimum_stock_level' => 1000,
                'image_url' => 'ayam.jpg',
                'ingredient_category_id' => 2,
            ],
            [
                'id' => 7,
                'name' => 'Santan Kelapa',
                'unit' => 'ml',
                'price_per_unit' => 30.00,
                'description' => 'Santan kental murni',
                'stock_quantity' => 5000,
                'minimum_stock_level' => 200,
                'image_url' => 'santan.jpg',
                'ingredient_category_id' => 5,
            ],
            [
                'id' => 8,
                'name' => 'Bumbu Nasi Goreng Spesial',
                'unit' => 'sachet',
                'price_per_unit' => 3000.00,
                'description' => 'Bumbu praktis untuk nasi goreng pedas',
                'stock_quantity' => 200,
                'minimum_stock_level' => 20,
                'image_url' => 'bumbu_nasgor.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 9,
                'name' => 'Kecap Manis Premium',
                'unit' => 'botol',
                'price_per_unit' => 12000.00,
                'description' => 'Kecap manis kental dari kedelai hitam',
                'stock_quantity' => 100,
                'minimum_stock_level' => 10,
                'image_url' => 'kecap_manis.jpg',
                'ingredient_category_id' => 4,
            ],
            [
                'id' => 10,
                'name' => 'Beras Putih Premium',
                'unit' => 'kg',
                'price_per_unit' => 14000.00,
                'description' => 'Beras pulen wangi pandan',
                'stock_quantity' => 500,
                'minimum_stock_level' => 50,
                'image_url' => 'beras.jpg',
                'ingredient_category_id' => 3,
            ],
            [
                'id' => 11,
                'name' => 'Telur Ayam Negeri',
                'unit' => 'kg',
                'price_per_unit' => 28000.00,
                'description' => 'Telur ayam segar sumber protein',
                'stock_quantity' => 100,
                'minimum_stock_level' => 10,
                'image_url' => 'telur.jpg',
                'ingredient_category_id' => 2,
            ],
            [
                'id' => 12,
                'name' => 'Bumbu Sayur Asem',
                'unit' => 'sachet',
                'price_per_unit' => 2500.00,
                'description' => 'Racikan bumbu asem segar',
                'stock_quantity' => 150,
                'minimum_stock_level' => 20,
                'image_url' => 'bumbu_asem.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 13,
                'name' => 'Paket Sayuran Asem',
                'unit' => 'bungkus',
                'price_per_unit' => 5000.00,
                'description' => 'Paket berisi jagung, melinjo, labu siam, kacang panjang',
                'stock_quantity' => 50,
                'minimum_stock_level' => 5,
                'image_url' => 'paket_sayur_asem.jpg',
                'ingredient_category_id' => 5,
            ],
            [
                'id' => 14,
                'name' => 'Ikan Gurame Segar',
                'unit' => 'kg',
                'price_per_unit' => 45000.00,
                'description' => 'Ikan gurame hidup fresh',
                'stock_quantity' => 40,
                'minimum_stock_level' => 5,
                'image_url' => 'gurame.jpg',
                'ingredient_category_id' => 2,
            ],
            [
                'id' => 15,
                'name' => 'Saus Tiram',
                'unit' => 'botol',
                'price_per_unit' => 18000.00,
                'description' => 'Saus tiram gurih untuk tumisan',
                'stock_quantity' => 75,
                'minimum_stock_level' => 10,
                'image_url' => 'saus_tiram.jpg',
                'ingredient_category_id' => 4,
            ],
            [
                'id' => 16,
                'name' => 'Garam Dapur Halus',
                'unit' => 'bungkus',
                'price_per_unit' => 3000.00,
                'description' => 'Garam beryodium untuk segala masakan',
                'stock_quantity' => 500,
                'minimum_stock_level' => 50,
                'image_url' => 'garam.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 17,
                'name' => 'Gula Pasir Putih',
                'unit' => 'kg',
                'price_per_unit' => 16000.00,
                'description' => 'Gula tebu murni',
                'stock_quantity' => 300,
                'minimum_stock_level' => 30,
                'image_url' => 'gula_pasir.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 18,
                'name' => 'Merica Bubuk',
                'unit' => 'botol',
                'price_per_unit' => 5000.00,
                'description' => 'Lada putih bubuk murni',
                'stock_quantity' => 100,
                'minimum_stock_level' => 10,
                'image_url' => 'merica.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 19,
                'name' => 'Bawang Putih Kating',
                'unit' => 'kg',
                'price_per_unit' => 40000.00,
                'description' => 'Bawang putih bonggol besar wangi',
                'stock_quantity' => 50,
                'minimum_stock_level' => 5,
                'image_url' => 'bawang_putih.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 20,
                'name' => 'Bawang Merah Brebes',
                'unit' => 'kg',
                'price_per_unit' => 35000.00,
                'description' => 'Bawang merah lokal kualitas super',
                'stock_quantity' => 50,
                'minimum_stock_level' => 5,
                'image_url' => 'bawang_merah.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 21,
                'name' => 'Ketumbar Bubuk',
                'unit' => 'sachet',
                'price_per_unit' => 1000.00,
                'description' => 'Rempah penyedap aroma',
                'stock_quantity' => 200,
                'minimum_stock_level' => 20,
                'image_url' => 'ketumbar.jpg',
                'ingredient_category_id' => 1,
            ],

            [
                'id' => 22,
                'name' => 'Udang Peci Segar',
                'unit' => 'kg',
                'price_per_unit' => 85000.00,
                'description' => 'Udang laut ukuran sedang',
                'stock_quantity' => 30,
                'minimum_stock_level' => 5,
                'image_url' => 'udang.jpg',
                'ingredient_category_id' => 2,
            ],
            [
                'id' => 23,
                'name' => 'Cumi-Cumi Segar',
                'unit' => 'kg',
                'price_per_unit' => 90000.00,
                'description' => 'Cumi laut segar siap masak',
                'stock_quantity' => 25,
                'minimum_stock_level' => 5,
                'image_url' => 'cumi.jpg',
                'ingredient_category_id' => 2,
            ],
            [
                'id' => 24,
                'name' => 'Daging Giling Sapi',
                'unit' => 'kg',
                'price_per_unit' => 135000.00,
                'description' => 'Cocok untuk bola daging atau tumisan',
                'stock_quantity' => 40,
                'minimum_stock_level' => 5,
                'image_url' => 'daging_giling.jpg',
                'ingredient_category_id' => 2,
            ],
            [
                'id' => 25,
                'name' => 'Bakso Sapi Halus',
                'unit' => 'bungkus',
                'price_per_unit' => 25000.00,
                'description' => 'Isi 25 butir, daging sapi asli',
                'stock_quantity' => 60,
                'minimum_stock_level' => 10,
                'image_url' => 'bakso_sapi.jpg',
                'ingredient_category_id' => 2,
            ],
            [
                'id' => 26,
                'name' => 'Sosis Sapi Premium',
                'unit' => 'bungkus',
                'price_per_unit' => 45000.00,
                'description' => 'Sosis bratwurst isi 5',
                'stock_quantity' => 50,
                'minimum_stock_level' => 10,
                'image_url' => 'sosis.jpg',
                'ingredient_category_id' => 2,
            ],
            [
                'id' => 27,
                'name' => 'Fillet Dada Ayam',
                'unit' => 'kg',
                'price_per_unit' => 55000.00,
                'description' => 'Daging ayam tanpa tulang dan kulit',
                'stock_quantity' => 80,
                'minimum_stock_level' => 10,
                'image_url' => 'fillet_ayam.jpg',
                'ingredient_category_id' => 2,
            ],

            [
                'id' => 28,
                'name' => 'Tepung Terigu Protein Sedang',
                'unit' => 'kg',
                'price_per_unit' => 12000.00,
                'description' => 'Tepung serbaguna segitiga',
                'stock_quantity' => 200,
                'minimum_stock_level' => 20,
                'image_url' => 'terigu.jpg',
                'ingredient_category_id' => 3,
            ],
            [
                'id' => 29,
                'name' => 'Tepung Tapioka / Kanji',
                'unit' => 'bungkus',
                'price_per_unit' => 8000.00,
                'description' => 'Untuk membuat cilok atau pengental',
                'stock_quantity' => 100,
                'minimum_stock_level' => 10,
                'image_url' => 'tapioka.jpg',
                'ingredient_category_id' => 3,
            ],
            [
                'id' => 30,
                'name' => 'Mie Telur Kering',
                'unit' => 'bungkus',
                'price_per_unit' => 6000.00,
                'description' => 'Mie kuning kering pipih',
                'stock_quantity' => 150,
                'minimum_stock_level' => 20,
                'image_url' => 'mie_telur.jpg',
                'ingredient_category_id' => 3,
            ],
            [
                'id' => 31,
                'name' => 'Bihun Jagung',
                'unit' => 'bungkus',
                'price_per_unit' => 7500.00,
                'description' => 'Bihun kenyal tidak mudah hancur',
                'stock_quantity' => 120,
                'minimum_stock_level' => 15,
                'image_url' => 'bihun.jpg',
                'ingredient_category_id' => 3,
            ],
            [
                'id' => 32,
                'name' => 'Tepung Roti / Panir',
                'unit' => 'bungkus',
                'price_per_unit' => 10000.00,
                'description' => 'Remah roti kasar untuk lapisan krispi',
                'stock_quantity' => 80,
                'minimum_stock_level' => 10,
                'image_url' => 'panir.jpg',
                'ingredient_category_id' => 3,
            ],

            [
                'id' => 33,
                'name' => 'Saus Tomat',
                'unit' => 'botol',
                'price_per_unit' => 12000.00,
                'description' => 'Saus tomat merah segar',
                'stock_quantity' => 100,
                'minimum_stock_level' => 10,
                'image_url' => 'saus_tomat.jpg',
                'ingredient_category_id' => 4,
            ],
            [
                'id' => 34,
                'name' => 'Saus Sambal Ekstra Pedas',
                'unit' => 'botol',
                'price_per_unit' => 15000.00,
                'description' => 'Saus sambal pedas nampol',
                'stock_quantity' => 120,
                'minimum_stock_level' => 15,
                'image_url' => 'saus_pedas.jpg',
                'ingredient_category_id' => 4,
            ],
            [
                'id' => 35,
                'name' => 'Kecap Asin',
                'unit' => 'botol',
                'price_per_unit' => 8000.00,
                'description' => 'Penyedap rasa asin gurih',
                'stock_quantity' => 90,
                'minimum_stock_level' => 10,
                'image_url' => 'kecap_asin.jpg',
                'ingredient_category_id' => 4,
            ],
            [
                'id' => 36,
                'name' => 'Minyak Wijen',
                'unit' => 'botol',
                'price_per_unit' => 28000.00,
                'description' => 'Minyak aroma khas chinese food',
                'stock_quantity' => 60,
                'minimum_stock_level' => 5,
                'image_url' => 'minyak_wijen.jpg',
                'ingredient_category_id' => 4,
            ],
            [
                'id' => 37,
                'name' => 'Mayones Serbaguna',
                'unit' => 'sachet',
                'price_per_unit' => 5000.00,
                'description' => 'Mayones creamy untuk salad/cocolan',
                'stock_quantity' => 200,
                'minimum_stock_level' => 20,
                'image_url' => 'mayones.jpg',
                'ingredient_category_id' => 4,
            ],

            [
                'id' => 38,
                'name' => 'Tahu Putih Sutra',
                'unit' => 'kotak',
                'price_per_unit' => 5000.00,
                'description' => 'Tahu lembut isi 4 potong',
                'stock_quantity' => 50,
                'minimum_stock_level' => 10,
                'image_url' => 'tahu.jpg',
                'ingredient_category_id' => 5,
            ],
            [
                'id' => 39,
                'name' => 'Tempe Daun',
                'unit' => 'papan',
                'price_per_unit' => 4000.00,
                'description' => 'Tempe kedelai fermentasi bungkus daun',
                'stock_quantity' => 60,
                'minimum_stock_level' => 10,
                'image_url' => 'tempe.jpg',
                'ingredient_category_id' => 5,
            ],
            [
                'id' => 40,
                'name' => 'Wortel Brastagi',
                'unit' => 'kg',
                'price_per_unit' => 12000.00,
                'description' => 'Wortel manis impor segar',
                'stock_quantity' => 40,
                'minimum_stock_level' => 5,
                'image_url' => 'wortel.jpg',
                'ingredient_category_id' => 5,
            ],
            [
                'id' => 41,
                'name' => 'Kentang Dieng',
                'unit' => 'kg',
                'price_per_unit' => 18000.00,
                'description' => 'Kentang kuning besar',
                'stock_quantity' => 50,
                'minimum_stock_level' => 5,
                'image_url' => 'kentang.jpg',
                'ingredient_category_id' => 5,
            ],
            [
                'id' => 42,
                'name' => 'Cabe Merah Keriting',
                'unit' => 'kg',
                'price_per_unit' => 60000.00,
                'description' => 'Cabe merah segar pedas sedang',
                'stock_quantity' => 30,
                'minimum_stock_level' => 5,
                'image_url' => 'cabe_keriting.jpg',
                'ingredient_category_id' => 5,
            ],
            [
                'id' => 43,
                'name' => 'Brokoli Hijau',
                'unit' => 'bonggol',
                'price_per_unit' => 15000.00,
                'description' => 'Sayuran hijau kaya serat',
                'stock_quantity' => 25,
                'minimum_stock_level' => 5,
                'image_url' => 'brokoli.jpg',
                'ingredient_category_id' => 5,
            ],
            [
                'id' => 44,
                'name' => 'Ikat Kangkung Segar',
                'unit' => 'ikat',
                'price_per_unit' => 3000.00,
                'description' => 'Kangkung segar hijau dari petani lokal',
                'stock_quantity' => 100,
                'minimum_stock_level' => 15,
                'image_url' => 'kangkung.jpg',
                'ingredient_category_id' => 5,
            ],
            [
                'id' => 45,
                'name' => 'Terasi Udang',
                'unit' => 'sachet',
                'price_per_unit' => 2000.00,
                'description' => 'Terasi udang khas untuk sambal',
                'stock_quantity' => 200,
                'minimum_stock_level' => 30,
                'image_url' => 'terasi.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 46,
                'name' => 'Jahe Segar',
                'unit' => 'kg',
                'price_per_unit' => 20000.00,
                'description' => 'Jahe segar aromatik',
                'stock_quantity' => 40,
                'minimum_stock_level' => 5,
                'image_url' => 'jahe.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 47,
                'name' => 'Kunyit Segar',
                'unit' => 'kg',
                'price_per_unit' => 15000.00,
                'description' => 'Kunyit segar warna kuning cerah',
                'stock_quantity' => 35,
                'minimum_stock_level' => 5,
                'image_url' => 'kunyit.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 48,
                'name' => 'Lengkuas / Laos',
                'unit' => 'kg',
                'price_per_unit' => 15000.00,
                'description' => 'Lengkuas segar penambah aroma masakan',
                'stock_quantity' => 30,
                'minimum_stock_level' => 5,
                'image_url' => 'lengkuas.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 49,
                'name' => 'Serai Wangi',
                'unit' => 'ikat',
                'price_per_unit' => 2000.00,
                'description' => 'Serai segar beraroma wangi',
                'stock_quantity' => 120,
                'minimum_stock_level' => 20,
                'image_url' => 'serai.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 50,
                'name' => 'Daun Salam & Jeruk',
                'unit' => 'bungkus',
                'price_per_unit' => 2000.00,
                'description' => 'Daun aromatik untuk masakan Nusantara',
                'stock_quantity' => 150,
                'minimum_stock_level' => 20,
                'image_url' => 'daun_salam.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 51,
                'name' => 'Kemiri Bulat',
                'unit' => 'bungkus',
                'price_per_unit' => 5000.00,
                'description' => 'Kemiri utuh kualitas bagus',
                'stock_quantity' => 80,
                'minimum_stock_level' => 10,
                'image_url' => 'kemiri.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 52,
                'name' => 'Bumbu Kacang / Pecel',
                'unit' => 'bungkus',
                'price_per_unit' => 12000.00,
                'description' => 'Bumbu kacang siap pakai',
                'stock_quantity' => 60,
                'minimum_stock_level' => 10,
                'image_url' => 'bumbu_kacang.jpg',
                'ingredient_category_id' => 1,
            ],
            [
                'id' => 53,
                'name' => 'Tauge Segar',
                'unit' => 'kg',
                'price_per_unit' => 8000.00,
                'description' => 'Tauge segar bersih dan renyah',
                'stock_quantity' => 30,
                'minimum_stock_level' => 5,
                'image_url' => 'tauge.jpg',
                'ingredient_category_id' => 5,
            ],
            [
                'id' => 54,
                'name' => 'Jeruk Nipis',
                'unit' => 'kg',
                'price_per_unit' => 18000.00,
                'description' => 'Jeruk nipis segar asam alami',
                'stock_quantity' => 25,
                'minimum_stock_level' => 5,
                'image_url' => 'jeruk_nipis.jpg',
                'ingredient_category_id' => 5,
            ],
            [
                'id' => 55,
                'name' => 'Bawang Goreng Renyah',
                'unit' => 'toples',
                'price_per_unit' => 10000.00,
                'description' => 'Bawang goreng renyah siap tabur',
                'stock_quantity' => 70,
                'minimum_stock_level' => 10,
                'image_url' => 'bawang_goreng.jpg',
                'ingredient_category_id' => 1,
            ],
        ];

        foreach ($ingredients as $ingredient) {
            DB::table('ingredients')->updateOrInsert(['id' => $ingredient['id']], array_merge($ingredient, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
